{
  "permissions": {
    "allow": [
      "mcp__desktop-commander__read_process_output",
      "mcp__desktop-commander__start_process",
      "mcp__plugin_discord_discord__download_attachment",
      "mcp__plugin_discord_discord__reply",
      "Bash(node:*)",
      "Bash(tasklist)",
      "Bash(wmic process:*)",
      "Bash(powershell:*)",
      "Bash(pip show:*)",
      "Bash(python -m edge_tts --list-voices)",
      "Bash(gh auth *)",
      "Bash(gh repo *)",
      "Bash(git --version)",
      "Bash(git config *)",
      "Bash(npx claude-mem *)",
      "WebFetch(domain:github.com)",
      "Bash(python -c \"import json,sys; d=json.load\\(sys.stdin\\); print\\(json.dumps\\(d.get\\('enabledPlugins', {}\\), indent=2\\)\\)\")",
      "Bash(claude plugin *)",
      "Bash(npx ecc-agentshield *)",
      "Bash(git clone *)",
      "Bash(pip install *)",
      "Bash(python *)",
      "Bash(claude *)",
      "Bash(wait)",
      "Bash(claude-flow *)",
      "Bash(npm list *)",
      "Bash(npm view *)",
      "Bash(pip list *)",
      "Bash(pip index *)",
      "Bash(grep -v \"^$\")",
      "WebFetch(domain:raw.githubusercontent.com)",
      "Bash(gh api *)",
      "WebFetch(domain:api.github.com)",
      "Bash(powershell.exe *)",
      "Bash(wsl --list --verbose)",
      "Bash(taskkill *)",
      "Bash(bash *)",
      "Bash(npm install *)",
      "Bash(npm run *)",
      "Skill(react-components)",
      "mcp__claude_ai_Notion__notion-fetch",
      "mcp__claude_ai_Notion__notion-update-page",
      "mcp__claude_ai_Notion__notion-create-database",
      "mcp__claude_ai_Notion__notion-create-pages",
      "mcp__claude_ai_Notion__notion-create-view"
    ]
  }
}
